import { useEffect, useState } from "react";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Package, ArrowLeft, Barcode } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { generateCode } from "@/utils/codeGenerator";
import { Checkbox } from "@/components/ui/checkbox";
import { MasterDataTable, ColumnDef } from "@/components/master-data/MasterDataTable";
import { getBadgeVariant } from "@/utils/badgeColors";
import { apiEndpoints } from "@/lib/api";

interface Product {
  id: number;
  sku: string;
  code?: string; // New Code (user input)
  old_code?: string; // Old Code (user input)
  new_code?: string; // New Code (user input)
  name: string;
  generic_name?: string; // Optional generic name
  base_price: number | string;
  unit_of_measure: string;
  is_active: boolean;
  primary_packaging?: "Bottle" | "Blister" | "Vial" | "Injection";
  product_type_commercial?: boolean;
  product_type_sample?: boolean;
  product_type_institutional?: boolean;
  product_type_export?: boolean;
  ifc_value1?: number;
  ifc_value2?: number;
  ifc_result?: number;
  mc_value1?: number;
  mc_value2?: number;
  mc_value3?: number;
  mc_result?: number;
  business_unit?: string;  // Pharma, Purnava, Animal health
  hsn_code?: string;
}

export default function Products() {
  const { toast } = useToast();
  const [showAddForm, setShowAddForm] = useState(false);
  const [editMode, setEditMode] = useState(false);
  const [selectedProduct, setSelectedProduct] = useState<Product | null>(null);
  const [products, setProducts] = useState<Product[]>([]);
  const [loading, setLoading] = useState(true);

  const [formData, setFormData] = useState({
    old_code: "",
    new_code: "",
    name: "",
    generic_name: "",
    unit_of_measure: "",
    business_unit: "" as "Pharma" | "Purnava" | "Animal health" | "",
    primary_packaging: "" as "Bottle" | "Blister" | "Vial" | "Injection" | "",
    product_type_commercial: false,
    product_type_sample: false,
    product_type_institutional: false,
    product_type_export: false,
    ifc_value1: "",
    ifc_value2: "",
    mc_value1: "",
    mc_value2: "",
    mc_value3: "",
  });
  
  const [newProductSku, setNewProductSku] = useState<string>("");

  // Calculate IFC result
  const ifcResult = formData.ifc_value1 && formData.ifc_value2 
    ? parseFloat(formData.ifc_value1) * parseFloat(formData.ifc_value2)
    : null;

  // Calculate MC result
  const mcResult = formData.mc_value1 && formData.mc_value2 && formData.mc_value3
    ? parseFloat(formData.mc_value1) * parseFloat(formData.mc_value2) * parseFloat(formData.mc_value3)
    : null;

  // Fetch products from API
  useEffect(() => {
    fetchProducts();
  }, []);

  const fetchProducts = async () => {
    try {
      setLoading(true);
      const data = await apiEndpoints.products.getAll();
      setProducts(data);
    } catch (error) {
      console.error("Failed to fetch products:", error);
      toast({
        title: "Error",
        description: "Failed to load products. Please try again.",
        variant: "destructive",
      });
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    document.title = "Products | App";
  }, []);

  // Generate SKU when form opens for new product (will be auto-generated by backend)
  useEffect(() => {
    if (showAddForm && !editMode) {
      setNewProductSku("PRD-XXXX"); // Placeholder, will be generated by backend
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [showAddForm, editMode]);

  const handleAdd = async () => {
    try {
      const productData: any = {
        name: formData.name,
        old_code: formData.old_code || undefined,
        new_code: formData.new_code || undefined,
        generic_name: formData.generic_name || undefined,
        base_price: 0,  // Default to 0, not editable in form
        unit_of_measure: formData.unit_of_measure || "PCS",
        business_unit: formData.business_unit || undefined,
        primary_packaging: formData.primary_packaging || undefined,
        product_type_commercial: formData.product_type_commercial,
        product_type_sample: formData.product_type_sample,
        product_type_institutional: formData.product_type_institutional,
        product_type_export: formData.product_type_export,
        ifc_value1: formData.ifc_value1 ? parseFloat(formData.ifc_value1) : undefined,
        ifc_value2: formData.ifc_value2 ? parseFloat(formData.ifc_value2) : undefined,
        ifc_result: ifcResult || undefined,
        mc_value1: formData.mc_value1 ? parseFloat(formData.mc_value1) : undefined,
        mc_value2: formData.mc_value2 ? parseFloat(formData.mc_value2) : undefined,
        mc_value3: formData.mc_value3 ? parseFloat(formData.mc_value3) : undefined,
        mc_result: mcResult || undefined,
        is_active: true,
      };

      if (editMode && selectedProduct) {
        await apiEndpoints.products.update(selectedProduct.id, productData);
        toast({
          title: "Product updated",
          description: "Product information has been updated successfully.",
        });
      } else {
        const newProduct = await apiEndpoints.products.create(productData);
        toast({
          title: "Product added",
          description: `New product created with SKU ${newProduct.sku}.`,
        });
      }
      
      await fetchProducts();
      resetForm();
    } catch (error: any) {
      console.error("Failed to save product:", error);
      toast({
        title: "Error",
        description: error.message || "Failed to save product. Please try again.",
        variant: "destructive",
      });
    }
  };

  const handleEdit = (product: Product) => {
    setSelectedProduct(product);
    setFormData({
      old_code: product.old_code || "",
      new_code: product.new_code || product.code || "",
      name: product.name,
      generic_name: product.generic_name || "",
      unit_of_measure: product.unit_of_measure || "",
      business_unit: product.business_unit || "",
      primary_packaging: product.primary_packaging || "",
      product_type_commercial: product.product_type_commercial || false,
      product_type_sample: product.product_type_sample || false,
      product_type_institutional: product.product_type_institutional || false,
      product_type_export: product.product_type_export || false,
      ifc_value1: product.ifc_value1?.toString() || "",
      ifc_value2: product.ifc_value2?.toString() || "",
      mc_value1: product.mc_value1?.toString() || "",
      mc_value2: product.mc_value2?.toString() || "",
      mc_value3: product.mc_value3?.toString() || "",
    });
    setNewProductSku(product.sku);
    setEditMode(true);
    setShowAddForm(true);
  };

  const handleDelete = async (product: Product) => {
    try {
      await apiEndpoints.products.delete(product.id);
      toast({
        title: "Product deleted",
        description: "The product has been removed from catalog.",
        variant: "destructive",
      });
      await fetchProducts();
    } catch (error: any) {
      console.error("Failed to delete product:", error);
      toast({
        title: "Error",
        description: error.message || "Failed to delete product. Please try again.",
        variant: "destructive",
      });
    }
  };

  const handleCancel = () => {
    resetForm();
  };

  const resetForm = () => {
    setFormData({
      old_code: "",
      new_code: "",
      name: "",
      generic_name: "",
      unit_of_measure: "",
      business_unit: "",
      primary_packaging: "",
      product_type_commercial: false,
      product_type_sample: false,
      product_type_institutional: false,
      product_type_export: false,
      ifc_value1: "",
      ifc_value2: "",
      mc_value1: "",
      mc_value2: "",
      mc_value3: "",
    });
    setNewProductSku("");
    setEditMode(false);
    setSelectedProduct(null);
    setShowAddForm(false);
  };

  const handleChange = (field: string, value: string) => {
    setFormData(prev => ({ ...prev, [field]: value }));
  };

  // Define table columns (Old Code and New Code instead of SKU)
  const columns: ColumnDef<Product>[] = [
    {
      key: "name",
      header: "Product Name",
      render: (_, product) => (
        <span className="font-medium">{product.name}</span>
      ),
    },
    {
      key: "old_code",
      header: "Old Code",
      render: (value) => (
        <span className="font-mono font-semibold text-muted-foreground bg-muted px-2 py-1 rounded">
          {value || "-"}
        </span>
      ),
    },
    {
      key: "new_code",
      header: "New Code",
      render: (value, product) => (
        <span className="font-mono font-semibold text-primary bg-primary/10 px-2 py-1 rounded">
          {value || product.code || "-"}
        </span>
      ),
    },
    {
      key: "generic_name",
      header: "Generic Name",
      render: (value) => (
        <span className="text-muted-foreground">{value || "-"}</span>
      ),
    },
    {
      key: "unit_of_measure",
      header: "UOM",
      render: (value) => (
        <Badge variant="outline" className="text-xs">
          {String(value)}
        </Badge>
      ),
    },
  ];

  // Show form page if showAddForm is true
  if (showAddForm) {
    return (
      <main className="p-6">
        <header className="mb-6">
          <div className="flex items-center gap-3 mb-2">
            <Button
              variant="ghost"
              size="sm"
              onClick={handleCancel}
              className="gap-2"
            >
              <ArrowLeft className="h-4 w-4" />
              Back
            </Button>
            <Package className="h-6 w-6 text-primary" />
            <h1 className="text-2xl font-semibold text-foreground">
              {editMode ? "Edit Product" : "Add New Product"}
            </h1>
          </div>
          <p className="text-sm text-muted-foreground">
            {editMode ? "Update product information" : "Create a new product in the catalog"}
          </p>
        </header>

        <Card className="card-elevated">
          <CardContent className="p-6">
            <div className="space-y-6 max-w-4xl">
              {/* SKU Field - Auto-generated */}
              <div className="space-y-2">
                <Label htmlFor="sku" className="flex items-center gap-2">
                  <Barcode className="h-4 w-4 text-muted-foreground" />
                  SKU / Product Code *
                </Label>
                <Input
                  id="sku"
                  value={editMode && selectedProduct?.sku ? selectedProduct.sku : newProductSku}
                  disabled
                  className="bg-muted font-mono font-semibold"
                  placeholder="Auto-generated"
                />
                <p className="text-xs text-muted-foreground">Auto-generated SKU (cannot be changed)</p>
              </div>

              {/* Code Fields - User input */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="old-code">Old Code</Label>
                  <Input
                    id="old-code"
                    value={formData.old_code}
                    onChange={(e) => handleChange("old_code", e.target.value)}
                    placeholder="Enter old code"
                  />
                  <p className="text-xs text-muted-foreground">Manually enter the old product code</p>
                </div>
                <div className="space-y-2">
                  <Label htmlFor="new-code">New Code</Label>
                  <Input
                    id="new-code"
                    value={formData.new_code}
                    onChange={(e) => handleChange("new_code", e.target.value)}
                    placeholder="Enter new code"
                  />
                  <p className="text-xs text-muted-foreground">Manually enter the new product code</p>
                </div>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="name">Product Name *</Label>
                  <Input
                    id="name"
                    value={formData.name}
                    onChange={(e) => handleChange("name", e.target.value)}
                    placeholder="Enter product name"
                    required
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="generic-name">Generic Name</Label>
                  <Input
                    id="generic-name"
                    value={formData.generic_name}
                    onChange={(e) => handleChange("generic_name", e.target.value)}
                    placeholder="Enter generic name (optional)"
                  />
                  <p className="text-xs text-muted-foreground">Optional generic name for the product</p>
                </div>
              </div>

              {/* Product Type */}
              <div className="space-y-3">
                <Label>Product Type</Label>
                <div className="flex flex-wrap items-center gap-6">
                  <div className="flex items-center space-x-2">
                    <Checkbox 
                      id="product-type-commercial"
                      checked={formData.product_type_commercial}
                      onCheckedChange={(checked) => 
                        setFormData(prev => ({
                          ...prev,
                          product_type_commercial: checked === true
                        }))
                      }
                    />
                    <Label htmlFor="product-type-commercial" className="font-normal cursor-pointer">
                      Commercial
                    </Label>
                  </div>
                  <div className="flex items-center space-x-2">
                    <Checkbox 
                      id="product-type-sample"
                      checked={formData.product_type_sample}
                      onCheckedChange={(checked) => 
                        setFormData(prev => ({
                          ...prev,
                          product_type_sample: checked === true
                        }))
                      }
                    />
                    <Label htmlFor="product-type-sample" className="font-normal cursor-pointer">
                      Sample
                    </Label>
                  </div>
                  <div className="flex items-center space-x-2">
                    <Checkbox 
                      id="product-type-institutional"
                      checked={formData.product_type_institutional}
                      onCheckedChange={(checked) => 
                        setFormData(prev => ({
                          ...prev,
                          product_type_institutional: checked === true
                        }))
                      }
                    />
                    <Label htmlFor="product-type-institutional" className="font-normal cursor-pointer">
                      Institutional
                    </Label>
                  </div>
                  <div className="flex items-center space-x-2">
                    <Checkbox 
                      id="product-type-export"
                      checked={formData.product_type_export}
                      onCheckedChange={(checked) => 
                        setFormData(prev => ({
                          ...prev,
                          product_type_export: checked === true
                        }))
                      }
                    />
                    <Label htmlFor="product-type-export" className="font-normal cursor-pointer">
                      Export
                    </Label>
                  </div>
                </div>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="business-unit">Business Unit</Label>
                  <Select value={formData.business_unit} onValueChange={(val) => handleChange("business_unit", val)}>
                    <SelectTrigger id="business-unit">
                      <SelectValue placeholder="Select business unit" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="Pharma">Pharma</SelectItem>
                      <SelectItem value="Purnava">Purnava</SelectItem>
                      <SelectItem value="Animal health">Animal health</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </div>
              
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="unit">UOM *</Label>
                  <Select value={formData.unit_of_measure} onValueChange={(val) => handleChange("unit_of_measure", val)}>
                    <SelectTrigger id="unit">
                      <SelectValue placeholder="Select" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="PCS">PCS</SelectItem>
                      <SelectItem value="pack">pack</SelectItem>
                      <SelectItem value="box">box</SelectItem>
                      <SelectItem value="kg">kg</SelectItem>
                      <SelectItem value="liter">liter</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </div>

              {/* Primary Packaging */}
              <div className="space-y-2">
                <Label htmlFor="primary-packaging">Primary Packaging</Label>
                <Select 
                  value={formData.primary_packaging} 
                  onValueChange={(val) => handleChange("primary_packaging", val)}
                >
                  <SelectTrigger id="primary-packaging">
                    <SelectValue placeholder="Select primary packaging" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="Bottle">Bottle</SelectItem>
                    <SelectItem value="Blister">Blister</SelectItem>
                    <SelectItem value="Vial">Vial</SelectItem>
                    <SelectItem value="Injection">Injection</SelectItem>
                  </SelectContent>
                </Select>
              </div>

              {/* Pack Size */}
              <div className="border-t pt-6 mt-6">
                <Label className="text-base font-semibold mb-4 block">Pack Size</Label>
                
                {/* IFC Section */}
                <div className="space-y-4 mb-6">
                  <div className="flex items-center gap-2 mb-2">
                    <Label className="font-medium">IFC</Label>
                  </div>
                  <div className="grid grid-cols-4 gap-2 items-center">
                    <Input
                      type="number"
                      value={formData.ifc_value1}
                      onChange={(e) => handleChange("ifc_value1", e.target.value)}
                      placeholder="5"
                      className="text-center"
                    />
                    <span className="text-center">×</span>
                    <Input
                      type="number"
                      value={formData.ifc_value2}
                      onChange={(e) => handleChange("ifc_value2", e.target.value)}
                      placeholder="10"
                      className="text-center"
                    />
                    <div className="flex items-center gap-2">
                      <span className="text-center font-medium">=</span>
                      <Input
                        value={ifcResult !== null ? ifcResult.toString() : ""}
                        disabled
                        className="bg-muted font-semibold text-center"
                        placeholder="Result"
                      />
                    </div>
                  </div>
                </div>

                {/* MC Section */}
                <div className="space-y-4">
                  <div className="flex items-center gap-2 mb-2">
                    <Label className="font-medium">MC</Label>
                  </div>
                  <div className="grid grid-cols-6 gap-2 items-center">
                    <Input
                      type="number"
                      value={formData.mc_value1}
                      onChange={(e) => handleChange("mc_value1", e.target.value)}
                      placeholder="18"
                      className="text-center"
                    />
                    <span className="text-center">×</span>
                    <Input
                      type="number"
                      value={formData.mc_value2}
                      onChange={(e) => handleChange("mc_value2", e.target.value)}
                      placeholder="5"
                      className="text-center"
                    />
                    <span className="text-center">×</span>
                    <Input
                      type="number"
                      value={formData.mc_value3}
                      onChange={(e) => handleChange("mc_value3", e.target.value)}
                      placeholder="10"
                      className="text-center"
                    />
                    <div className="flex items-center gap-2">
                      <span className="text-center font-medium">=</span>
                      <Input
                        value={mcResult !== null ? mcResult.toString() : ""}
                        disabled
                        className="bg-muted font-semibold text-center"
                        placeholder="Result"
                      />
                    </div>
                  </div>
                </div>
              </div>

              <div className="flex justify-end gap-4 pt-6 border-t">
                <Button variant="outline" onClick={handleCancel}>
                  Cancel
                </Button>
                <Button onClick={handleAdd}>
                  {editMode ? "Update Product" : "Create Product"}
                </Button>
              </div>
            </div>
          </CardContent>
        </Card>
      </main>
    );
  }

  // Show list view
  return (
    <main className="p-6">
      <header className="mb-6">
        <div className="flex items-center gap-3 mb-2">
          <Package className="h-6 w-6 text-primary" />
          <h1 className="text-2xl font-semibold text-foreground">Product Management</h1>
        </div>
        <p className="text-sm text-muted-foreground">Manage product catalog, SKUs, and inventory items</p>
      </header>

      <MasterDataTable
        title="Product Catalog"
        description={`Total products: ${products.length}`}
        data={products}
        columns={columns}
        searchPlaceholder="Search products..."
        searchFields={["name", "old_code", "new_code", "code", "generic_name"]}
        itemsPerPage={10}
        onAdd={() => setShowAddForm(true)}
        onEdit={handleEdit}
        onDelete={handleDelete}
        emptyMessage="No products found"
        showCode={false}
      />
    </main>
  );
}
